<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.2" tiledversion="1.3.3" name="tileset1" tilewidth="4" tileheight="4" tilecount="1024" columns="32">
 <image source="../../resources/spritesheets/tilesets/testtiles1.png" width="128" height="128"/>
 <tile id="0" type="Ground"/>
 <tile id="1" type="Ground"/>
 <tile id="2" type="Ground"/>
 <tile id="3" type="Ground"/>
 <tile id="4" type="Ground"/>
 <tile id="5" type="Ground"/>
 <tile id="6" type="Ground"/>
 <tile id="7" type="Ground"/>
 <tile id="8" type="Ground"/>
 <tile id="9" type="Ground"/>
 <tile id="26" type="Ground"/>
 <tile id="27" type="Ground"/>
 <tile id="28" type="Ground"/>
 <tile id="29" type="Ground"/>
 <tile id="30" type="Ground"/>
 <tile id="31" type="Ground"/>
 <tile id="58" type="Ground"/>
 <tile id="63" type="Ground"/>
 <tile id="90" type="Ground"/>
 <tile id="91" type="Ground"/>
 <tile id="92" type="Ground"/>
 <tile id="93" type="Ground"/>
 <tile id="94" type="Ground"/>
 <tile id="95" type="Ground"/>
 <tile id="122" type="Ground"/>
 <tile id="123" type="Ground"/>
 <tile id="124" type="Ground"/>
 <tile id="125" type="Ground"/>
 <tile id="126" type="Ground"/>
 <tile id="127" type="Ground"/>
 <tile id="154" type="Ground"/>
 <tile id="155" type="Ground"/>
 <tile id="156" type="Ground"/>
 <tile id="157" type="Ground"/>
 <tile id="158" type="Ground"/>
 <tile id="159" type="Ground"/>
 <tile id="896" type="Ground"/>
 <tile id="897" type="Ground"/>
 <tile id="898" type="Ground"/>
 <tile id="899" type="Ground"/>
 <tile id="900" type="Ground"/>
 <tile id="901" type="Ground"/>
 <tile id="902" type="Ground"/>
 <tile id="903" type="Ground"/>
 <tile id="904" type="Ground"/>
 <tile id="905" type="Ground"/>
 <tile id="906" type="Ground"/>
 <tile id="907" type="Ground"/>
 <tile id="928" type="Ground"/>
 <tile id="939" type="Ground"/>
 <tile id="960" type="Ground"/>
 <tile id="971" type="Ground"/>
 <tile id="992" type="Ground"/>
 <tile id="993" type="Ground"/>
 <tile id="994" type="Ground"/>
 <tile id="995" type="Ground"/>
 <tile id="996" type="Ground"/>
 <tile id="997" type="Ground"/>
 <tile id="998" type="Ground"/>
 <tile id="999" type="Ground"/>
 <tile id="1000" type="Ground"/>
 <tile id="1001" type="Ground"/>
 <tile id="1002" type="Ground"/>
 <tile id="1003" type="Ground"/>
</tileset>
